# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47c37a66fda341833d62ec40f322e1e09399033c0a2460af26065fe622ec337af41c9f047c9a9b30c3f2cd9cb68a455e4437404a041b274e0139bfec264693b3

test:
  secret_key_base: e571274d85d23895cd3b79886418007170cfaf08ce73c35efd870dcd9a88a4e40d6d6d1723c955b8a33681f5335950c83264496df7fe9f09e2294f8ada8e83c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
